apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: stir
spec:
  type: ClusterIP   # exposé désormais via l'Ingress, plus besoin de LoadBalancer ici
  selector: { app: frontend }
  ports: [{ port: 80, targetPort: 80 }]