apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: stir
spec:
  clusterIP: None   # headless service, requis pour un StatefulSet
  selector: { app: mongodb }
  ports: [{ port: 27017, targetPort: 27017 }]