apiVersion: v1
kind: ConfigMap
metadata:
  name: stir-config
  namespace: stir
data:
  SERVER_PORT: "8080"
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/stirworkflow"
  PYTHON_API_URL: "http://model:5000"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"